// 全自动批量替换 CN 字典里的 ?? 占位符
// 基于上下文关键词识别(每个 key 后面是字面占位符 + ')
// 策略:穷举所有已知 key,匹配 "key: '??' 或 '???...'" 形式,基于全局字典映射到中文
const fs = require('fs');
const path = require('path');

// 通用中文映射表(从已有修复的 notes.tsx / zotero.tsx 等抽出)
const CN_MAP = {
  // 通用
  'addNote': '加笔记',
  'addRead': '加入阅读',
  'addTask': '加任务',
  'addToPath': '加入路径',
  'all': '全部',
  'allChapters': '所有章节',
  'allStatus': '所有状态',
  'allTags': '所有标签',
  'allYears': '所有年份',
  'allType': '所有类型',
  'author': '作者',
  'authors': '作者',
  'cancel': '取消',
  'chapter': '章节',
  'chapters': '章节',
  'chapterList': '章节列表',
  'clearFilter': '清除筛选',
  'close': '关闭',
  'confirm': '确认',
  'copy': '复制',
  'create': '创建',
  'createdAt': '创建时间',
  'date': '日期',
  'day': '日',
  'days': '天',
  'delete': '删除',
  'detail': '详情',
  'description': '描述',
  'draft': '草稿',
  'edit': '编辑',
  'endDate': '结束日期',
  'export': '导出',
  'filter': '筛选',
  'finished': '已完成',
  'freeform': '自由写作',
  'from': '起',
  'hint': '提示',
  'id': '编号',
  'inProgress': '进行中',
  'importance': '重要度',
  'info': '信息',
  'keyword': '关键词',
  'keywords': '关键词',
  'label': '标签',
  'level': '级别',
  'loading': '加载中',
  'log': '日志',
  'markDone': '标记完成',
  'meta': '元数据',
  'month': '月',
  'name': '名称',
  'new': '新建',
  'newNote': '新建笔记',
  'newTask': '新建任务',
  'next': '下一个',
  'noData': '暂无数据',
  'note': '笔记',
  'notes': '笔记',
  'open': '打开',
  'options': '选项',
  'overview': '概览',
  'paper': '文献',
  'papers': '文献',
  'path': '路径',
  'platform': '平台',
  'prev': '上一个',
  'priority': '优先级',
  'progress': '进度',
  'project': '项目',
  'quarter': '季度',
  'rank': '排名',
  'recent': '最近',
  'related': '相关',
  'remove': '移除',
  'reset': '重置',
  'review': '复习',
  'role': '角色',
  'save': '保存',
  'search': '搜索',
  'section': '板块',
  'selectAll': '全选',
  'selected': '已选',
  'settings': '设置',
  'share': '分享',
  'shortcut': '快捷键',
  'show': '显示',
  'source': '来源',
  'startDate': '开始日期',
  'status': '状态',
  'submit': '提交',
  'summary': '摘要',
  'sync': '同步',
  'tag': '标签',
  'tags': '标签',
  'task': '任务',
  'tasks': '任务',
  'template': '模板',
  'time': '时间',
  'title': '标题',
  'to': '至',
  'today': '今天',
  'tomorrow': '明天',
  'tool': '工具',
  'tools': '工具',
  'total': '共',
  'type': '类型',
  'update': '更新',
  'updatedAt': '更新时间',
  'url': '链接',
  'value': '值',
  'view': '查看',
  'week': '周',
  'year': '年',
  'yesterday': '昨天',

  // 工作台 / Workbench
  'addReading': '加入阅读',
  'addToNotes': '加入笔记',
  'addToTask': '加入任务',
  'advanced': '进阶',
  'allScenes': '全部场景',
  'background': '背景',
  'beginner': '入门',
  'catalog': '目录',
  'check': '查看',
  'citeCount': '被引数',
  'citedBy': '被引数',
  'context': '上下文',
  'copyCitation': '复制引用',
  'created': '创建于',
  'cropped': '已截取',
  'current': '当前',
  'details': '详情',
  'disabled': '已禁用',
  'drafts': '草稿',
  'empty': '暂无',
  'examples': '示例',
  'expected': '预期',
  'exportJson': '导出 JSON',
  'exportMd': '导出 Markdown',
  'exportPdf': '导出 PDF',
  'fillTemplate': '填充模板',
  'generate': '生成',
  'goal': '目标',
  'high': '高',
  'history': '历史',
  'inReview': '在审',
  'input': '输入',
  'intermediate': '中级',
  'language': '语言',
  'last7days': '最近 7 天',
  'lastUpdated': '最近更新',
  'list': '列表',
  'medium': '中',
  'metric': '指标',
  'newVersion': '新版本',
  'noActive': '未选中',
  'noNote': '暂无笔记',
  'noPaper': '暂无文献',
  'noResult': '无结果',
  'noTask': '暂无任务',
  'openLibrary': '打开文献库',
  'openSource': '打开来源',
  'orderBy': '排序',
  'outline': '大纲',
  'output': '输出',
  'preview': '预览',
  'priority_high': '高优先级',
  'priority_low': '低优先级',
  'progressRate': '完成率',
  'rating': '评分',
  'ratio': '压缩率',
  'raw': '原文',
  'read': '阅读',
  'readAt': '阅读于',
  'readingPath': '阅读路线',
  'readingPaths': '阅读路线',
  'reading': '在读',
  'ready': '就绪',
  'rebuild': '重建',
  'recent_added': '最近添加',
  'recent_read': '最近阅读',
  'recentlyRead': '最近阅读',
  'relevance': '相关度',
  'reload': '重新加载',
  'report': '报告',
  'rest': '其余',
  'result': '结果',
  'role_paper': '文献',
  'rows': '行',
  'run': '运行',
  'running': '运行中',
  'saveAt': '保存于',
  'savedAt': '保存于',
  'scene': '场景',
  'scenes': '场景',
  'select': '选择',
  'selectChapter': '选择章节',
  'showLess': '收起',
  'showMore': '展开',
  'size': '大小',
  'skip': '跳过',
  'sortBy': '排序方式',
  'speed': '速度',
  'standard': '标准',
  'standards': '标准',
  'start': '开始',
  'started': '已开始',
  'stats': '统计',
  'step': '步骤',
  'stop': '停止',
  'subject': '主题',
  'subtitle': '副标题',
  'success': '成功',
  'syncNow': '立即同步',
  'tab_overview': '概览',
  'tab_detail': '详情',
  'tab_notes': '笔记',
  'tab_task': '任务',
  'tab_relate': '相关',
  'theme': '主题',
  'theme_dark': '深色',
  'theme_light': '浅色',
  'theme_system': '跟随系统',
  'thisMonth': '本月',
  'thisWeek': '本周',
  'tips': '小贴士',
  'todo': '待办',
  'treeView': '树形视图',
  'try': '试一下',
  'unread': '未读',
  'unselectAll': '取消全选',
  'updated': '已更新',
  'upload': '上传',
  'usecase': '使用场景',
  'useCases': '使用场景',
  'version': '版本',
  'weekday': '工作日',
  'year2': '年',
  'zoology': '领域',
  'zotero': 'Zotero',
  'algorithm': '算法',
  'allAlgo': '所有算法',
  'arch': '架构',
  'baseline': '基线',
  'bench': '基准',
  'benchmark': '基准',
  'bookmark': '书签',
  'category': '分类',
  'chooseChapter': '选择章节',
  'classic': '经典',
  'compare': '对比',
  'compress': '压缩',
  'compression': '压缩',
  'content': '内容',
  'course': '课程',
  'data': '数据',
  'decompress': '解压',
  'depth': '深度',
  'description_zh': '简介',
  'doc': '文档',
  'document': '文档',
  'docs': '文档',
  'duration': '时长',
  'entry': '条目',
  'equipment': '设备',
  'err': '错误',
  'event': '事件',
  'example': '示例',
  'extra': '额外',
  'feed': '订阅',
  'field': '字段',
  'file': '文件',
  'files': '文件',
  'folder': '文件夹',
  'format': '格式',
  'formula': '公式',
  'freq': '频率',
  'grade': '等级',
  'graph': '关系图',
  'guide': '指南',
  'help': '帮助',
  'highlight': '高亮',
  'home': '首页',
  'icon': '图标',
  'i18n': '国际化',
  'id2': '编号',
  'import': '导入',
  'index': '索引',
  'indicator': '指标',
  'isPublic': '公开',
  'item': '条目',
  'items': '条目',
  'kind': '类型',
  'kpi': '指标',
  'language_zh': '中文',
  'language_en': '英文',
  'layout': '布局',
  'leaderboard': '排行榜',
  'link': '链接',
  'links': '链接',
  'live': '直播',
  'locale': '语言',
  'logOut': '退出登录',
  'login': '登录',
  'logout': '退出',
  'main': '主要',
  'map': '地图',
  'markRead': '标记已读',
  'markdown': 'Markdown',
  'match': '匹配',
  'matches': '匹配项',
  'matrix': '矩阵',
  'max': '最大',
  'menu': '菜单',
  'method': '方法',
  'min': '最小',
  'mode': '模式',
  'model': '模型',
  'module': '模块',
  'msg': '消息',
  'msgError': '错误',
  'msgOk': '成功',
  'myLibrary': '我的文献库',
  'myNotes': '我的笔记',
  'myTasks': '我的任务',
  'nav': '导航',
  'newer': '较新',
  'nextPage': '下一页',
  'noMatch': '无匹配',
  'noProject': '暂无项目',
  'noSelection': '未选择',
  'note2': '笔记',
  'numCitations': '被引数',
  'older': '较旧',
  'on': '开',
  'off': '关',
  'onlyMine': '只看我的',
  'openPaper': '打开文献',
  'openTask': '打开任务',
  'option': '选项',
  'order': '顺序',
  'pageTitle': '页面标题',
  'paperCount': '文献数',
  'paper2': '文献',
  'param': '参数',
  'parameters': '参数',
  'params': '参数',
  'password': '密码',
  'path2': '路径',
  'pdf': 'PDF',
  'pdfOnly': '仅 PDF',
  'pipeline': '流程',
  'placeholder': '占位符',
  'plan': '计划',
  'point': '点',
  'pos': '位置',
  'prevPage': '上一页',
  'preview2': '预览',
  'private': '私有',
  'profile': '档案',
  'project2': '项目',
  'projects': '项目',
  'public': '公开',
  'push': '推送',
  'quality': '质量',
  'query': '查询',
  'queue': '队列',
  'quote': '引用',
  'rank2': '排名',
  'rate': '评分',
  'rawText': '原文',
  'reGenerate': '重新生成',
  'reader': '读者',
  'recent2': '最近',
  'record': '记录',
  'records': '记录',
  'refresh': '刷新',
  'register': '注册',
  'release': '发布',
  'repo': '仓库',
  'reset2': '重置',
  'resultCount': '结果数',
  'richText': '富文本',
  'role_admin': '管理员',
  'role_user': '用户',
  'row': '行',
  'rows2': '行',
  'safe': '安全',
  'scenario': '场景',
  'score': '得分',
  'screen': '屏幕',
  'search2': '搜索',
  'searchResult': '搜索结果',
  'section2': '章节',
  'sections': '章节',
  'selected2': '已选',
  'sentences': '句子',
  'session': '会话',
  'set': '设置',
  'settings2': '设置',
  'showAll': '显示全部',
  'sidebar': '侧栏',
  'simple': '简单',
  'single': '单个',
  'site': '站点',
  'size2': '大小',
  'slide': '幻灯',
  'snippet': '片段',
  'sort': '排序',
  'source2': '来源',
  'source2_kind': '来源类型',
  'span': '跨度',
  'star': '收藏',
  'starred': '已收藏',
  'stars': '收藏数',
  'start2': '开始',
  'stat': '统计',
  'status2': '状态',
  'step2': '步骤',
  'style': '样式',
  'subject2': '主题',
  'submit2': '提交',
  'subType': '子类型',
  'summary2': '摘要',
  'system': '系统',
  'tab': '标签页',
  'tag2': '标签',
  'tags2': '标签',
  'tagsHint': '用逗号分隔多个标签',
  'target': '目标',
  'template2': '模板',
  'temp': '临时',
  'test': '测试',
  'text': '文本',
  'theme2': '主题',
  'thread': '线程',
  'thumb': '缩略图',
  'time2': '时间',
  'timeline': '时间线',
  'title2': '标题',
  'todo2': '待办',
  'toggle': '切换',
  'toolbar': '工具栏',
  'tooltip': '提示',
  'topic': '主题',
  'topics': '主题',
  'total2': '共',
  'track': '追踪',
  'tree': '树',
  'treemap': '树状图',
  'type2': '类型',
  'types': '类型',
  'unit': '单位',
  'unsaved': '未保存',
  'url2': '链接',
  'usage': '使用',
  'use': '使用',
  'user': '用户',
  'username': '用户名',
  'users': '用户',
  'value2': '值',
  'version2': '版本',
  'video': '视频',
  'view2': '查看',
  'viewDetail': '查看详情',
  'viewPaper': '查看文献',
  'week2': '周',
  'wordCount': '字数',
  'work': '工作',
  'works': '工作',
  'year2': '年',
  'zh': '中文',
  // ============= 第二批:具体页面 keys =============
  'add': '新增',
  'allAuthors': '所有作者',
  'alternatives': '替代方案',
  'ambiguous': '模糊',
  'attachToLit': '关联到文献',
  'autoCreateLit': '自动创建文献',
  'cite': '引用',
  'clear': '清除',
  'colAct': '操作',
  'colAuthor': '作者',
  'colDiff': '难度',
  'colPri': '优先级',
  'colTitle': '标题',
  'colYear': '年份',
  'connected': '已连接',
  'copyLog': '复制日志',
  'coreReason': '核心原因',
  'count': '数量',
  'daily': '每天',
  'desc': '说明',
  'dialogNew': '新建对话框',
  'dialogTitleLabel': '标题',
  'difficulty': '难度',
  'disconnect': '断开',
  'disconnected': '未连接',
  'done': '已完成',
  'dup': '重复',
  'expStatus': '实验状态',
  'experiments': '实验',
  'external': '外部',
  'fetched': '已获取',
  'fetchedAt': '获取时间',
  'filterAll': '全部',
  'filterUnread': '只看未读',
  'hide': '隐藏',
  'hourly': '每小时',
  'hours': '小时',
  'impact': '影响',
  'inPath': '在路径中',
  'interval': '间隔',
  'isDup': '重复',
  'lane': '车道',
  'laneNeedsExp': '需要实验',
  'laneNeedsNote': '需要笔记',
  'laneNeedsReport': '需要报告',
  'laneThisWeek': '本周',
  'lastSync': '上次同步',
  'legend': '图例',
  'legendLane': '泳道',
  'legendStatus': '状态',
  'logCount': '日志条数',
  'manual': '手动',
  'matchMatched': '已匹配',
  'matchPending': '待匹配',
  'matched': '已匹配',
  'matchedCount': '匹配数',
  'modules': '模块',
  'more': '更多',
  'moveTo': '移动到',
  'needsReview': '需复核',
  'newPapers': '新文献',
  'nextSync': '下次同步',
  'noteDone': '笔记已完成',
  'noteDraft': '笔记草稿',
  'noteWriting': '正在写笔记',
  'of': '之',
  'oneLine': '一句话',
  'openExp': '打开实验',
  'openLit': '打开文献',
  'pending': '待处理',
  'pickLane': '选择车道',
  'pickMinutes': '分钟数',
  'pickPriority': '优先级',
  'problem': '问题',
  'readPaper': '阅读文献',
  'readerBenefit': '读者收益',
  'readingList': '阅读清单',
  'reason': '原因',
  'references': '参考文献',
  'refs': '相关',
  'reject': '拒绝',
  'risk': '风险',
  'runExperiment': '运行实验',
  'sortChapter': '按章节',
  'sortPriority': '按优先级',
  'sortTitle': '按标题',
  'sourcesOn': '来源已开',
  'statusNote': '笔记状态',
  'statusRead': '阅读状态',
  'syncing': '同步中',
  'tableMgmt': '表格管理',
  'unknown': '未知',
  'unmatched': '未匹配',
  'usage2': '用途',
  'usage3': '用法',
  'usageTitle': '使用场景',
  'viewInLibrary': '在文献库查看',
  'whyRead': '为何读',
  'yearOverview': '年度概览',

  // ============= 第三批:混合字符串值(部分问号)=============
  'accept': '加入文献库',
  'refreshSim': '刷新模拟',
  'autoPullAttachments': '拉取附件',
  'autoPullNotes': '拉取笔记',
  'connect': '连接 Zotero',
  'logEmpty': '日志为空',
  'noKey': '未配置 API Key',
  'userId': '用户 ID',
  'attachPicker': '关联到文献库',
  'searchLit': '搜索文献',
  'searchItems': '搜索条目',
  'searchItem': '搜索条目',
  'noItems': '暂无条目',
  'noLog': '暂无日志',
  'usage1': '用法:阅读 / 笔记 / Zotero 同步',
  'pickDue': '截止(可选)',
  'sortYearAsc': '年份↑',
  'sortYearDesc': '年份↓',
  'duration': '时长(可选)',
  'searchPh': '搜索关键词',
  'laneNeedsPdf': '需 PDF',
  'intro': '入门',
  'hard': '困难',
  'showAll': '显示全部',

  // ============= 第四批:含 Zotero 的混合 =============
  'matchedLit': 'Zotero 已匹配',
  'statusZotero': 'Zotero 状态',
};

// 处理文件
const files = process.argv.slice(2);
if (files.length === 0) {
  console.log('Usage: node fix-cn.js <files>');
  process.exit(1);
}

for (const f of files) {
  let s = fs.readFileSync(f, 'utf8');
  let n = 0;
  let partialN = 0;
  // 匹配 "key: '???'" 全问号形式(对象字面量)
  const reFull = /(\b[a-zA-Z_][a-zA-Z0-9_]*)\s*:\s*'(\?+)'(,?)/g;
  s = s.replace(reFull, (m, key, val, comma) => {
    const cn = CN_MAP[key];
    if (cn) {
      n++;
      return `${key}: '${cn}'${comma}`;
    }
    return m;
  });
  // 匹配 "key: '???xxx'" 含问号的混合形式
  const rePart = /(\b[a-zA-Z_][a-zA-Z0-9_]*)\s*:\s*'([^']*\?+[^']*)'(,?)/g;
  s = s.replace(rePart, (m, key, val, comma) => {
    if (/^\?+$/.test(val)) return m;
    const cn = CN_MAP[key];
    if (cn) {
      partialN++;
      return `${key}: '${cn}'${comma}`;
    }
    return m;
  });
  // 匹配 '???': '...'(字面字典 key,key 是问号)
  // 这种情况下,key 是占位符,需要根据 value 推断中文 label
  // 先收集所有 '??': '#color' 形式,根据颜色顺序推断(蓝/橙/绿/灰 = 奠基/必读/推荐/参考)
  const dictKeyRe = /'(\?+)'\s*:\s*'((?:[^'\\]|\\.)*)'/g;
  const dictMappings = [
    ['奠基', '#1d4ed8'],  // 蓝
    ['必读', '#b45309'],  // 橙
    ['推荐', '#0d9488'],  // 绿
    ['参考', '#64748b'],  // 灰
  ];
  let dictN = 0;
  s = s.replace(dictKeyRe, (m, key, val) => {
    for (const [cn, color] of dictMappings) {
      if (val === color) {
        dictN++;
        return `'${cn}': '${val}'`;
      }
    }
    return m;
  });

  fs.writeFileSync(f, s, 'utf8');
  console.log(`${f}: replaced ${n} (full) + ${partialN} (partial) + ${dictN} (dict-key)`);
}